[package]
name = "tmp"
version = "0.1.0"
authors = ["lucas"]

[dependencies]
log = { version = "0.4", features = ["std", "serde"] }
ctor = "0.1.20"
strum = { version = "0.24.0", features = ["derive"] }

[dev-dependencies]
lazy_static = "1.4.0"